# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tunepipe < Formula
  desc "A minimal TUI music player powered by yt-dlp"
  homepage "https://github.com/Arnel-rah/tunepipe"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Arnel-rah/tunepipe/releases/download/v0.2.0/tunepipe_darwin_amd64.tar.gz"
      sha256 "2d8a709ccae5e398324a136f0ad41bbae92975d930db9161d4305da7148b6a44"

      define_method(:install) do
        bin.install "tunepipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Arnel-rah/tunepipe/releases/download/v0.2.0/tunepipe_darwin_arm64.tar.gz"
      sha256 "dc3535b3c1636159e7f9c2ff53e88c53457695a7529b42ff27c185e2dcf4d8ba"

      define_method(:install) do
        bin.install "tunepipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Arnel-rah/tunepipe/releases/download/v0.2.0/tunepipe_linux_amd64.tar.gz"
      sha256 "2d835e5e57d14184117f3629f72da7f1c4ae5dda77577bd85ca28e1670e38322"
      define_method(:install) do
        bin.install "tunepipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Arnel-rah/tunepipe/releases/download/v0.2.0/tunepipe_linux_arm64.tar.gz"
      sha256 "51edbe0db8d7653fda770c04175b49444a9c3e374e4f5d07d18a1bc8d07270b4"
      define_method(:install) do
        bin.install "tunepipe"
      end
    end
  end
end
